In [133]:
from TFLite_detection_image import tflite_image_detection
import numpy as np
import cv2

box = []
image_path = 'img/test1.jpg'
class_path = 'pepper_class.txt'
model_path = 'pepper_detect_2cat_v3.tflite'
result = tflite_image_detection(class_path, model_path, image_path)
print(result)
for i in range(len(result)):
    if str(result[i][0]) == 'root':
        box = result[i]
        box.remove(box[0])
print(box)
# box = [259, 313, 295, 370]
src = cv2.imread(image_path)
src = src[box[1] - 10:box[3] + 10, box[0]:box[2] + 10]
src = cv2.GaussianBlur(src, (3, 3), 0)  # 高斯滤波
# img = cv2.cvtColor(src, cv2.COLOR_BGR2LAB)
cv2.imwrite('src.jpg', src)
img = src
Z = img.reshape((-1, 3))
# convert to np.float32
Z = np.float32(Z)
# define criteria, number of clusters(K) and apply kmeans()
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
K = 8
ret, label, center = cv2.kmeans(Z, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
# Now convert back into uint8, and make original image
center = np.uint8(center)
res = center[label.flatten()]
# for i in range(len(res)):
#     if res[i].all() == center[0].all():
#         res[i] = [255,0,0]
#     if res[i].all() == center[1].all():
#         res[i] = [0,255,0]
#     if res[i].all() == center[2].all():
#         res[i] = [0,0,255]
res2 = res.reshape(img.shape)
dst = cv2.applyColorMap(res2, cv2.COLORMAP_RAINBOW)
print(center)
# blur = cv2.GaussianBlur(res2, (5, 5), 0)
# res3, th3 = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow('res2', res2)
cv2.imwrite('kms.jpg',res2)
cv2.imshow('res2_', dst)
cv2.imwrite('visiualization.jpg', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

[0.77734375 0.77734375 0.39453125 0.37109375 0.19140625 0.16796875
 0.1484375  0.14453125 0.1328125  0.11328125]
[['pepper', 67, 21, 456, 365], ['root', 259, 313, 295, 370]]
[259, 313, 295, 370]
[[ 90 132 133]
 [ 18  31  38]
 [157 206 192]
 [ 71 108 114]
 [ 53  84  93]
 [ 28  43  57]
 [114 151 160]
 [ 39  60  75]]


In [134]:
from TFLite_detection_image import tflite_image_detection
import numpy as np
import cv2

box = []
image_path = 'img/test1.jpg'
class_path = 'pepper_class.txt'
model_path = 'pepper_detect_2cat_v3.tflite'
result = tflite_image_detection(class_path, model_path, image_path)
print(result)
for i in range(len(result)):
    if str(result[i][0]) == 'root':
        box = result[i]
        box.remove(box[0])
print(box)
# box = [259, 313, 295, 370]
src = cv2.imread(image_path)
src = src[box[1]:box[3], box[0]:box[2] + 10]
cv2.imshow('src', src)
cv2.waitKey(0)
cv2.destroyAllWindows()

[0.77734375 0.77734375 0.39453125 0.37109375 0.19140625 0.16796875
 0.1484375  0.14453125 0.1328125  0.11328125]
[['pepper', 67, 21, 456, 365], ['root', 259, 313, 295, 370]]
[259, 313, 295, 370]


In [35]:
src[src.shape[0]//2]

array([[ 42,  69,  89],
       [ 53,  77,  95],
       [ 64,  87, 103],
       [ 38,  59,  74],
       [ 49,  70,  85],
       [ 87, 108, 123],
       [ 84, 106, 118],
       [ 79, 100, 115],
       [ 68,  89, 104],
       [ 45,  65,  82],
       [ 26,  46,  64],
       [ 19,  38,  59],
       [  8,  26,  43],
       [  7,  22,  31],
       [ 18,  37,  42],
       [ 44,  68,  74],
       [ 67, 100, 103],
       [ 51,  92,  87],
       [ 34,  81,  72],
       [ 57, 107,  95],
       [ 65, 118, 104],
       [ 63, 118, 103],
       [ 72, 129, 114],
       [ 78, 137, 122],
       [ 76, 134, 123],
       [ 84, 141, 133],
       [ 30,  81,  83],
       [ 12,  55,  70],
       [ 22,  60,  84],
       [ 61,  97, 127],
       [ 85, 120, 154],
       [107, 142, 175],
       [132, 166, 196],
       [112, 146, 175],
       [ 69, 102, 128],
       [ 12,  42,  71],
       [  0,  21,  48],
       [  8,  35,  61],
       [ 56,  85, 106],
       [ 38,  66,  83],
       [ 14,  43,  58],
       [  0,  30

In [135]:
src[src.shape[0]//2]
Z = src[src.shape[0]//2].reshape((-1, 3))
Z = np.float32(Z)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
K = 2
ret, label, center = cv2.kmeans(Z, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
center = np.uint8(center)
res = center[label.flatten()]
print(center)
print(res)

[[ 78 116 126]
 [ 25  53  67]]
[[ 25  53  67]
 [ 25  53  67]
 [ 78 116 126]
 [ 25  53  67]
 [ 25  53  67]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 78 116 126]
 [ 25  53  67]
 [ 25  53  67]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 78 116 126]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 78 116 126]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]
 [ 25  53  67]]


In [ ]:
img_show = np.zeros(src.shape)
img_show[:] = res
img_show = np.uint8(img_show)
img_show = cv2.applyColorMap(img_show, cv2.COLORMAP_RAINBOW)
cv2.imshow('src', img_show)
cv2.waitKey(0)
cv2.destroyAllWindows()

# K-Means聚类实例

In [6]:
import numpy as np
import cv2
src = cv2.imread('img/littleduck.jpg')
src = cv2.GaussianBlur(src, (3, 3), 0)  # 高斯滤波
# img = cv2.cvtColor(src, cv2.COLOR_BGR2LAB)
img = src
Z = img.reshape((-1, 3))
# convert to np.float32
Z = np.float32(Z)
# define criteria, number of clusters(K) and apply kmeans()
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
K = 3
ret, label, center = cv2.kmeans(Z, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
# Now convert back into uint8, and make original image
center = np.uint8(center)
res = center[label.flatten()]
res2 = res.reshape(img.shape)
dst = cv2.applyColorMap(res2, cv2.COLORMAP_RAINBOW)
print(center)
# blur = cv2.GaussianBlur(res2, (5, 5), 0)
# res3, th3 = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow('res2', res2)
cv2.imshow('res2_', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[148 116  82]
 [106  86  60]
 [ 72 150 174]]
